### ISSUE TITLE
Warning: Task "default" not found

### ISSUE THREAD

**Issue by nagarjunbn** [kamiyam/grunt-cakephp#1]
Hi,
I executed the commands given .. On executing #grunt and # grunt --force , I am getting the below error.. And one clarification  will it also minify the .ctp files ..?

```
# grunt --force
Loading "Gruntfile.coffee" tasks...ERROR
>> TypeError: The super constructor to `inherits` must not be null or undefined.
Warning: Task "default" not found. Used --force, continuing.

Done, but with warnings.
```

**Comment by Sartxi** [comment]
I had the exact same thing happen

**Comment by nagarjunbn** [comment]
Inactive Repository . Closing the issue
